// ==UserScript==
// @name              Ziggy Chaturbate Suite
// @namespace         https://github.com/ryujo/roomgrid-multicam-pro
// @version           16.4.8
// @homepageURL       https://github.com/linuxNoob620/chaturbate-userscripts
// @supportURL        https://github.com/linuxNoob620/chaturbate-userscripts/issues
// @updateURL         https://raw.githubusercontent.com/linuxNoob620/chaturbate-userscripts/refs/heads/main/Chaturbate%20MultiCam%20Pro%20%2B%20Cam%20ARNA.meta.js
// @downloadURL       https://raw.githubusercontent.com/linuxNoob620/chaturbate-userscripts/refs/heads/main/Chaturbate%20MultiCam%20Pro%20%2B%20Cam%20ARNA.user.js
// @description       Native desktop and mobile RoomGrid suite with MultiCam, Cam ARNA, Reloaded tools, mobile Clean View, recording, split view, and encrypted settings sync.
// @author            Ziggy
// @license           MIT
// @match             https://chaturbate.com/*
// @match             https://*.chaturbate.com/*
// @require           https://cdn.jsdelivr.net/npm/hls.js@1.6.16/dist/hls.min.js
// @grant             GM_xmlhttpRequest
// @grant             GM_getValue
// @grant             GM_setValue
// @grant             GM_download
// @grant             window.focus
// @connect           archivebate.com
// @connect           recu.me
// @connect           showcamrips.com
// @connect           camshowrecordings.com
// @connect           camwh.com
// @connect           topcamvideos.com
// @connect           lovecamporn.com
// @connect           camwhores.tv
// @connect           bestcam.tv
// @connect           xhomealone.com
// @connect           stream-leak.com
// @connect           mfcamhub.com
// @connect           camshowrecord.net
// @connect           camwhoresbay.com
// @connect           camsave1.com
// @connect           onscreens.me
// @connect           livecamrips.to
// @connect           cumcams.cc
// @connect           allmy.cam
// @connect           livecamsrip.com
// @connect           camsrip.com
// @connect           translate.googleapis.com
// @connect           www.camsoda.com
// @connect           stripchat.com
// @connect           bongacams.com
// @connect           webchat.cam4.com
// @connect           cam4.com
// @connect           manifest-server.naiadsystems.com
// @connect           api-edge.myfreecams.com
// @connect           edgevideo.myfreecams.com
// @connect           api.github.com
// @run-at            document-end
// ==/UserScript==
